/**
 * SQL Script: Employee Bonus Report
 * 
 * Description:
 * This script creates the Employee and Bonus tables, inserts sample data based on the example,
 * and provides a query to report the name and bonus amount of each employee with a bonus less
 * than 1000. The result includes all employees, with null bonuses where no bonus exists or
 * bonus >= 1000.
 * 
 * Problem Statement:
 * Given the Employee and Bonus tables, report the name and bonus amount of each employee
 * with a bonus less than 1000. If an employee has no bonus, the bonus column should be null.
 * Return the result in any order.
 * 
 * Examples:
 * - Input: Employee table with empId, name, supervisor, salary; Bonus table with empId, bonus.
 * - Output: name, bonus (e.g., Brad|null, John|null, Dan|500)
 * 
 * Constraints:
 * - 0 <= number of employees <= 10^6
 * - -10^9 <= salary <= 10^9
 * - 0 <= bonus <= 10^9
 * 
 * Author: Generated by Grok 3 (xAI)
 * Date: 02:00 PM IST, Wednesday, July 30, 2025
 */

-- Drop tables if they exist to avoid conflicts
DROP TABLE IF EXISTS Bonus;
DROP TABLE IF EXISTS Employee;

-- Create Employee table
CREATE TABLE Employee (
    empId INT PRIMARY KEY,
    name VARCHAR(50),
    supervisor INT,
    salary INT
);

-- Create Bonus table with foreign key constraint
CREATE TABLE Bonus (
    empId INT PRIMARY KEY,
    bonus INT,
    FOREIGN KEY (empId) REFERENCES Employee(empId)
);

-- Insert sample data into Employee table
INSERT INTO Employee (empId, name, supervisor, salary) VALUES
(3, 'Brad', NULL, 4000),
(1, 'John', 3, 1000),
(2, 'Dan', 3, 2000),
(4, 'Thomas', 3, 4000);

-- Insert sample data into Bonus table
INSERT INTO Bonus (empId, bonus) VALUES
(2, 500),
(4, 2000);

-- Query to report employee names and bonuses less than 1000
/**
 * Query Description:
 * - Uses LEFT JOIN to include all employees from Employee table.
 * - Filters bonuses less than 1000 or null using WHERE clause.
 * - Returns name and bonus columns in any order.
 */
SELECT 
    e.name,
    b.bonus
FROM 
    Employee e
LEFT JOIN 
    Bonus b ON e.empId = b.empId
WHERE 
    b.bonus < 1000 OR b.bonus IS NULL;
