/**
 * SQL Script: Weather Temperature Increase Report
 * 
 * Description:
 * This script creates a weather table, inserts sample data, and provides a query to identify
 * days where the temperature is higher than the previous day. The result includes the id
 * of such weather records.
 * 
 * Problem Statement:
 * Given a weather table with id, recordDate, and temperature, find all records where the
 * temperature on a given day is higher than the temperature on the previous day (defined
 * as a difference of 1 day in recordDate). Return the id of these records.
 * 
 * Examples:
 * - Input: Weather table with consecutive dates and temperatures.
 * - Output: id of records where temperature increases (e.g., id 2 if temp on day 2 > temp on day 1).
 * 
 * Constraints:
 * - 0 <= number of records <= 10^6
 * - recordDate is a valid date
 * - -50 <= temperature <= 50
 * 
 * Author: Generated by Grok 3 (xAI)
 * Date: 02:26 PM IST, Wednesday, July 30, 2025
 */

-- Drop table if it exists to avoid conflicts
DROP TABLE IF EXISTS weather;

-- Create weather table
CREATE TABLE weather (
    id INT PRIMARY KEY,
    recordDate DATE,
    temperature INT
);

-- Insert sample data into weather table
INSERT INTO weather (id, recordDate, temperature) VALUES
(1, '2023-01-01', 10),
(2, '2023-01-02', 15),
(3, '2023-01-03', 12),
(4, '2023-01-04', 18),
(5, '2023-01-05', 16);

-- Query to find days with higher temperature than the previous day
/**
 * Query Description:
 * - Uses SELF JOIN to compare each record with the previous day's record.
 * - DATEDIFF ensures a 1-day difference between recordDate values.
 * - WHERE clause filters for temperature increases.
 * - Returns id of records meeting the condition.
 */
SELECT 
    w1.id
FROM 
    weather w1
JOIN 
    weather w2 ON DATEDIFF(w1.recordDate, w2.recordDate) = 1
WHERE 
    w1.temperature > w2.temperature;
